#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d ● ● ● ● ● ●
wmname LG3D

bspc config border_width         2
bspc config window_gap          5
bspc config focus_follows_pointer true
bspc config focused_border_color "#fcb7ff"
bspc config normal_border_color "#121420"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#for cursor
xsetroot -cursor_name left_ptr &
